[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
# better deterministic deploys
bytecode_hash = "none"
remappings = [
    "forge-std/=dependencies/forge-std-1.9.6/src/",
    "solady/=dependencies/solady-0.1.12/src/",
    "create2-helpers/=dependencies/create2-helpers-0.5.0/src/",
    "@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.2.0/src/",
    "@openzeppelin-contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.2.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "deterministic-proxy-factory/=src/",
]
optimizer_runs = 9999999
via_ir = true
solc_version = "0.8.29"

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
line_length = 100
single_line_statement_blocks = "multi"
sort_imports = true
contract_new_lines = true
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
multline_func_header = "all"

[dependencies]
forge-std = "1.9.6"
solady = "0.1.12"
create2-helpers = "0.5.0"
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
